SELECT
  DISTINCT PRODUCTID,
  TRIM(PRODUCTNAME) AS PRODUCTNAME,
  SUPPLIERID,
  CATEGORYID,
  TRIM(QUANTITYPERUNIT) AS QUANTITYPERUNIT,
  TRY_CAST(UNITPRICE AS FLOAT) AS UNITPRICE,
  TRY_CAST(UNITSINSTOCK AS INTEGER) AS UNITSINSTOCK,
  TRY_CAST(UNITSONORDER AS INTEGER) AS UNITSONORDER,
  TRY_CAST(REORDERLEVEL AS INTEGER) AS REORDERLEVEL,
  TRY_CAST(DISCONTINUED AS INTEGER) AS DISCONTINUED
FROM
    {{ source('sources', 'products') }}
WHERE PRODUCTID IS NOT NULL