SELECT
	DISTINCT (TRIM(ORDERID))::INT AS ORDERID,
	TRIM(PRODUCTID) AS PRODUCTID,
	TRIM(UNITPRICE) AS UNITPRICE ,
	TRIM(QUANTITY) AS QUANTITY ,
	TRIM(DISCOUNT) AS DISCOUNT 
FROM
    {{ source('sources', 'order_details') }}
WHERE ORDERID IS NOT NULL AND PRODUCTID IS NOT NULL