SELECT
  DISTINCT SUPPLIERID,
  TRIM(COMPANYNAME) AS COMPANYNAME,
  TRIM(CONTACTNAME) AS CONTACTNAME,
  TRIM(CONTACTTITLE) AS CONTACTTITLE,
  TRIM(ADDRESS) AS ADDRESS,
  TRIM(CITY) AS CITY,
  TRIM(REGION) AS REGION,
  TRIM(POSTALCODE) AS POSTALCODE,
  TRIM(COUNTRY) AS COUNTRY,
  REGEXP_REPLACE(TRIM(PHONE), '[^0-9]', '') AS PHONE,
  REGEXP_REPLACE(TRIM(FAX), '[^0-9]', '') AS FAX,
  TRIM(HOMEPAGE) AS HOMEPAGE
FROM
    {{ source('sources', 'suppliers') }}
WHERE SUPPLIERID IS NOT NULL