SELECT
  DISTINCT ORDERID,
  TRIM(CUSTOMERID) AS CUSTOMERID,
  EMPLOYEEID,
  TO_TIMESTAMP(ORDERDATE)::DATE AS ORDERDATE,
  TO_TIMESTAMP(REQUIREDDATE)::DATE AS REQUIREDDATE,
  TO_TIMESTAMP(SHIPPEDDATE)::DATE AS SHIPPEDDATE,
  SHIPVIA,
  TRY_CAST(FREIGHT AS FLOAT) AS FREIGHT,
  TRIM(SHIPNAME) AS SHIPNAME,
  TRIM(SHIPADDRESS) AS SHIPADDRESS,
  TRIM(SHIPCITY) AS SHIPCITY,
  TRIM(SHIPREGION) AS SHIPREGION,
  TRIM(SHIPPOSTALCODE) AS SHIPPOSTALCODE,
  TRIM(SHIPCOUNTRY) AS SHIPCOUNTRY
FROM
    {{ source('sources', 'orders') }}
WHERE ORDERID IS NOT NULL