SELECT
  DISTINCT CUSTOMERID,
  TRIM(COMPANYNAME) AS COMPANYNAME,
  COALESCE(LEFT(TRIM(CONTACTNAME), 200), 'UNKNOWN') AS CONTACTNAME,
  LEFT(TRIM(CONTACTTITLE), 200) AS CONTACTTITLE,
  LEFT(TRIM(ADDRESS), 200) AS ADDRESS,
  LEFT(TRIM(CITY), 15) AS CITY,
  COALESCE(LEFT(TRIM(REGION), 15), 'UNKNOWN') AS REGION,
  LEFT(TRIM(POSTALCODE), 10) AS POSTALCODE,
  LEFT(TRIM(COUNTRY), 15) AS COUNTRY,
  REGEXP_REPLACE(LEFT(TRIM(PHONE), 24), '[^0-9]', '') AS PHONE,
  REGEXP_REPLACE(LEFT(TRIM(FAX), 24), '[^0-9]', '') AS FAX    
FROM
    {{ source('sources', 'customers') }}
WHERE CUSTOMERID IS NOT NULL AND COMPANYNAME IS NOT NULL