x-airflow-common:
  &airflow-common
  image: dataninja/airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER}:${POSTGRES_PORT}/${POSTGRES_DB}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__TEST_CONNECTION=Enabled

    # For connecting to Postgres from Airflow
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
    - POSTGRES_PORT=${POSTGRES_PORT}    
    - POSTGRES_DB=${POSTGRES_DB}

    # For connecting to Postgres from Airflow
    - SNOWFLAKE_USER=${SNOWFLAKE_USER}
    - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
    - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
    - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
    - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
    - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
    - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
    
    - RESOURCE=${SOURCE}
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../scripts:/scripts

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER}
    hostname: ${POSTGRES_CONTAINER}    
    image: postgres:16
    restart: unless-stopped
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_PORT=${POSTGRES_PORT}    
    - POSTGRES_DB=${POSTGRES_DB}
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../sql:/sql
      - ../sql/conf/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "${POSTGRES_PORT}:5432"

  airflow-webserver:
    << : *airflow-common
    container_name: ${AIRFLOW_CONTAINER_WEBSERVER}
    hostname: ${AIRFLOW_CONTAINER_WEBSERVER}   
    command: airflow webserver
    entrypoint:
      - /scripts/auth-airflow.sh
    ports:
      - ${AIRFLOW_PORT}:8080
    restart: always

  airflow-scheduler:
    << : *airflow-common
    container_name: ${AIRFLOW_CONTAINER_SCHEDULER}
    hostname: ${AIRFLOW_CONTAINER_SCHEDULER} 
    command: airflow scheduler
    restart: always

networks:
  default:
    name: dataninja-networks
    external: true